<?php

namespace Database\Seeders;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('users')->insert([
            [
                'name' => 'Gabriel Armando',
                'first_surname' => 'Berrios',
                'second_surname' => 'Mendoza',
                'email' => 'admin@admin.com',
                'phone' => '1234567890',
                'role' => 1,
                'userid' => 1,
                'status' => 1,
                'password' => Hash::make('12345678'),
                'passwordUpdate' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ana María',
                'first_surname' => 'Pérez',
                'second_surname' => 'Sánchez',
                'email' => 'ana.perez@example.com',
                'phone' => '2345678901',
                'role' => 2,
                'userid' => 2,
                'status' => 1,
                'password' => Hash::make('password123'),
                'passwordUpdate' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Carlos ',
                'first_surname' => 'Martínez',
                'second_surname' => 'López',
                'email' => 'carlos.martinez@example.com',
                'phone' => '3456789012',
                'role' => 3,
                'userid' => 3,
                'status' => 1,
                'password' => Hash::make('password123'),
                'passwordUpdate' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sofía ',
                'first_surname' => 'Morales',
                'second_surname' => 'Castro',
                'email' => 'sofia.morales@example.com',
                'phone' => '4567890123',
                'role' => 2, 
                'userid' => 4,
                'status' => 1,
                'password' => Hash::make('password123'),
                'passwordUpdate' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gabriela Ruiz',
                'first_surname' => 'Ruiz',
                'second_surname' => 'García',
                'email' => 'gabriela.ruiz@example.com',
                'phone' => '5678901234',
                'role' => 3,
                'userid' => 5,
                'status' => 1,
                'password' => Hash::make('password123'),
                'passwordUpdate' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fernando Gómez',
                'first_surname' => 'Gómez',
                'second_surname' => 'Vega',
                'email' => 'fernando.gomez@example.com',
                'phone' => '6789012345',
                'role' => 3,
                'userid' => 6,
                'status' => 1,
                'password' => Hash::make('password123'),
                'passwordUpdate' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laura Sánchez',
                'first_surname' => 'Sánchez',
                'second_surname' => 'Moreno',
                'email' => 'laura.sanchez@example.com',
                'phone' => '7890123456',
                'role' => 2,
                'userid' => 7,
                'status' => 1,
                'password' => Hash::make('password123'),
                'passwordUpdate' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Javier Pérez',
                'first_surname' => 'Pérez',
                'second_surname' => 'Hernández',
                'email' => 'javier.perez@example.com',
                'phone' => '8901234567',
                'role' => 3,
                'userid' => 8,
                'status' => 1,
                'password' => Hash::make('password123'),
                'passwordUpdate' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Marta González',
                'first_surname' => 'González',
                'second_surname' => 'Rivas',
                'email' => 'marta.gonzalez@example.com',
                'phone' => '9012345678',
                'role' => 2,
                'userid' => 9,
                'status' => 1,
                'password' => Hash::make('password123'),
                'passwordUpdate' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Alejandro Torres',
                'first_surname' => 'Torres',
                'second_surname' => 'Álvarez',
                'email' => 'alejandro.torres@example.com',
                'phone' => '0123456789',
                'role' => 3, 
                'userid' => 10,
                'status' => 1,
                'password' => Hash::make('password123'),
                'passwordUpdate' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Carla Jiménez',
                'first_surname' => 'Jiménez',
                'second_surname' => 'Mendoza',
                'email' => 'carla.jimenez@example.com',
                'phone' => '1234567891',
                'role' => 2,
                'userid' => 11,
                'status' => 1,
                'password' => Hash::make('password123'),
                'passwordUpdate' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'José Luis García',
                'first_surname' => 'García',
                'second_surname' => 'Pérez',
                'email' => 'jose.garcia@example.com',
                'phone' => '2345678902',
                'role' => 3,
                'userid' => 12,
                'status' => 1,
                'password' => Hash::make('password123'),
                'passwordUpdate' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Elena Ruiz',
                'first_surname' => 'Ruiz',
                'second_surname' => 'Cano',
                'email' => 'elena.ruiz@example.com',
                'phone' => '3456789013',
                'role' => 2,
                'userid' => 13,
                'status' => 1,
                'password' => Hash::make('password123'),
                'passwordUpdate' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'David Hernández',
                'first_surname' => 'Hernández',
                'second_surname' => 'López',
                'email' => 'david.hernandez@example.com',
                'phone' => '4567890124',
                'role' => 3,
                'userid' => 14,
                'status' => 1,
                'password' => Hash::make('password123'),
                'passwordUpdate' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Isabel Martínez',
                'first_surname' => 'Martínez',
                'second_surname' => 'Cordero',
                'email' => 'isabel.martinez@example.com',
                'phone' => '5678901235',
                'role' => 2,
                'userid' => 15,
                'status' => 1,
                'password' => Hash::make('password123'),
                'passwordUpdate' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ricardo Gómez',
                'first_surname' => 'Gómez',
                'second_surname' => 'Vargas',
                'email' => 'ricardo.gomez@example.com',
                'phone' => '6789012346',
                'role' => 3,
                'userid' => 16,
                'status' => 1,
                'password' => Hash::make('password123'),
                'passwordUpdate' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lucía Vargas',
                'first_surname' => 'Vargas',
                'second_surname' => 'Morales',
                'email' => 'lucia.vargas@example.com',
                'phone' => '7890123457',
                'role' => 2,
                'userid' => 17,
                'status' => 1,
                'password' => Hash::make('password123'),
                'passwordUpdate' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Victor Salazar',
                'first_surname' => 'Salazar',
                'second_surname' => 'Jaramillo',
                'email' => 'victor.salazar@example.com',
                'phone' => '8901234568',
                'role' => 3,
                'userid' => 18,
                'status' => 1,
                'password' => Hash::make('password123'),
                'passwordUpdate' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paola Gómez',
                'first_surname' => 'Gómez',
                'second_surname' => 'Cardenas',
                'email' => 'paola.gomez@example.com',
                'phone' => '9012345679',
                'role' => 2, 
                'userid' => 19,
                'status' => 1,
                'password' => Hash::make('password123'),
                'passwordUpdate' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Andrés Moreno',
                'first_surname' => 'Moreno',
                'second_surname' => 'Gutiérrez',
                'email' => 'andres.moreno@example.com',
                'phone' => '0123456780',
                'role' => 3,
                'userid' => 20,
                'status' => 1,
                'password' => Hash::make('password123'),
                'passwordUpdate' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
